version: '3.8'

services:
  db:
    container_name: db
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  frontend:
    container_name: frontend
    image: mbigfly/foodgram_frontend:latest
    volumes:
      - frontend_value:/app/build/
    depends_on:
      - db
  backend:
    container_name: backend
    image: mbigfly/foodgram_backend:latest
    restart: always
    volumes:
      - static_value:/code/backend_static/
      - media_value:/code/backend_media/
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    image: nginx:1.19.3
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - frontend_value:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
      - static_value:/code/backend_static/
      - media_value:/code/backend_media/
    depends_on:
      - backend
      - frontend
volumes:
  postgres_data:
  frontend_value:
  static_value:
  media_value:


