version: '3.8'

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - ./.env

  frontend:
    image: mbigfly/foodgram_project_frontend:latest
    volumes:
      - ./frontend/:/app/result_build/
  backend:
    image: mbigfly/foodgram_project:latest
    command: >
      bash -c "python manage.py migrate &&  python manage.py collectstatic --noinput &&  python manage.py importingredients ingredients.json  &&  gunicorn --bind 0:8000 foodgram.wsgi"
    restart: always
    volumes:
      - static_backend_value:/app/static_backend/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
      - static_backend_value:/app/static_backend/
      - media_value:/app/media/
    depends_on:
      - backend
volumes:
  static_backend_value:
  media_value:


