version: '3.8'
services:

  db:
    image: postgres:13.0-alpine
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - ./.env

  frontend:
    image: mbigfly/foodgram_project_frontend:latest
    restart: always
    volumes:
      - frontend_value:/app/result_build/build/

  backend:
    image: mbigfly/foodgram_project:latest
    restart: always
    volumes:
      - static_value:/app/staticfiles/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - frontend_value:/var/html/frontend/
      - ./docs/:/var/html/frontend/api/docs/
      - static_value:/var/html/static_backend/
      - media_value:/var/html/media/
    depends_on:
      - backend
      - frontend

volumes:
  static_value:
  media_value:
  frontend_value:
